// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

package command

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("command.proto", fileDescriptor_command_00e3471b468ed2a7) }

var fileDescriptor_command_00e3471b468ed2a7 = []byte{
	// 44 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x62, 0x03, 0x53, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0f, 0x9f, 0xe4, 0x94, 0x17, 0x00, 0x00, 0x00,
}
